name: my-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - tqdm
  - torch
  - pip:
    - transformers
    - accelerate
    - bitsandbytes
    - triton
    - tiktoken
    - flash-attn
