name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - tqdm
  - pip
  - pip:
      - transformers
      - torch
      - accelerate
      - auto-gpt
      - bitsandbytes
